In [1]:
import pandas as pd
import numpy as np
import pyomo.environ as pyomo
from pyomo.opt import SolverStatus, TerminationCondition

Считаем данные, полученные на предыдущем этапе (для каждой модели "продукт - канал" был сохранён в csv файл датафрейм, содержащий откалиброванный скор и id клиента) и сведём их в общую таблицу

In [2]:
df1 = pd.read_csv(r'credit_call.csv')
df2 = pd.read_csv(r'credit_card_call.csv')
df3 = pd.read_csv(r'credit_card_sms.csv')
df4 = pd.read_csv(r'credit_sms.csv')

In [3]:
df1['product']='credit'
df2['product']='credit_card'
df3['product']='credit_card'
df4['product']='credit'
df1['channel']='call'
df2['channel']='call'
df3['channel']='sms'
df4['channel']='sms'

In [4]:
df=df1.merge(df2,how='outer').merge(df3,how='outer').merge(df4,how='outer')
df=df.loc[:,['client_id','product','channel','score']].sort_values(by=['client_id','product','channel'])
df['client_id']=df['client_id']+1
df.reset_index(drop=True,inplace=True)
df

       client_id      product channel     score
0              1       credit    call  0.999383
1              1       credit     sms  0.000081
2              1  credit_card    call  0.000171
3              1  credit_card     sms  0.000011
4              2       credit    call  0.000756
...          ...          ...     ...       ...
79995      19999  credit_card     sms  0.000010
79996      20000       credit    call  0.006400
79997      20000       credit     sms  0.003038
79998      20000  credit_card    call  0.014361
79999      20000  credit_card     sms  0.000219

[80000 rows x 4 columns]

Оптимизация при помощи Pyomo + GLPK

In [5]:
def optimize(frame: pd.DataFrame, channel_limits: dict, with_profit: bool) -> list:

    ds = frame.copy()
    
    #создание модели
    model = pyomo.ConcreteModel('model')
    
    #вектор бинарных переменных задачи
    model.x = pyomo.Var(range(ds.shape[0]), domain=pyomo.Binary, initialize=0)
    
    #вектор вероятностей
    P = list(ds.score)
    
    if(with_profit):
        #формирование колонки доходности по каждому клиенту в зависимости от пары "продукт-канал"
        ds['profit']=10000
        ds.loc[ds['product']=='credit_card','profit']=13000
        ds['profit'] = ds['profit'].astype(float)
        ds.loc[ds['channel']=='call','profit']-=50
        ds.loc[ds['channel']=='sms','profit']-=1.5
        #вектор доходности
        D = list(ds['profit'])
        #целевая функция с доходностью
        obj_expr = sum(D[i] * P[i] * model.x[i] for i in model.x)
    else:
        #целевая функция без доходности
        obj_expr = sum(P[i] * model.x[i] for i in model.x)

    model.obj = pyomo.Objective(expr=obj_expr, sense=pyomo.maximize)

    # объявление ограничений
    model.c = pyomo.ConstraintList()

    #ограничения на количество коммуникаций в каждом канале
    for channel in ds.channel.unique():
        model.c.add(sum(model.x[i] for i in list(ds[ds.channel==channel].index)) <= channel_limits[channel])

    #ограничения на количество продуктов для каждого клиента (не более одного продукта на клиента)
    for client in ds.client_id.unique():
        model.c.add(sum(model.x[i] for i in list(ds[ds.client_id==client].index)) <= 1)
        
    solver = pyomo.SolverFactory('glpk')
    results = solver.solve(model,timelimit=500)
    
    del ds
    
    if (results.solver.status == SolverStatus.ok) or (results.solver.termination_condition == TerminationCondition.optimal):
        print(results)
        print(model.obj())
        return [model.x[i].value for i in model.x]
    else:
        print ("Solver Status:",  result.solver.status)

In [6]:
#объем доступных коммуникаций в каналах
CHANNELS_LIMITS = {
    'call': 4000,
    'sms': 7000
}

Отимизация целевой функции без учёта доходности

In [7]:
optimal_decisions_1 = optimize(frame=df, channel_limits=CHANNELS_LIMITS, with_profit = False)
df['optimal_decision_1'] = optimal_decisions_1

#распределение продуктов в каналах
df[df['optimal_decision_1']==1].groupby(['channel', 'product']).\
                                    agg({'client_id': 'count'}).\
                                    rename(columns={'client_id': 'client_cnt'})

Problem:
- Name: unknown
  Lower bound: 3117.85426959603
  Upper bound: 3117.85426959603
  Number of objectives: 1
  Number of constraints: 20002
  Number of variables: 80000
  Number of nonzeros: 160000
  Sense: maximize
Solver:
- Status: ok
  Termination condition: optimal
  Statistics:
    Branch and bound:
      Number of bounded subproblems: 1
      Number of created subproblems: 1
  Error rc: 0
  Time: 44.27941942214966
Solution:
- number of solutions: 0
  number of solutions displayed: 0

3117.854269596032

                     client_cnt
channel product
call    credit             1860
        credit_card        2140
sms     credit             4439
        credit_card        2561

Отимизация целевой функции c учётом доходности

In [8]:
optimal_decisions_2 = optimize(frame=df, channel_limits=CHANNELS_LIMITS, with_profit = True)
df['optimal_decision_2'] = optimal_decisions_2

#распределение продуктов в каналах
df[df['optimal_decision_2']==1].groupby(['channel', 'product']).\
                                    agg({'client_id': 'count'}).\
                                    rename(columns={'client_id': 'client_cnt'})

Problem:
- Name: unknown
  Lower bound: 37071954.9039166
  Upper bound: 37071954.9039166
  Number of objectives: 1
  Number of constraints: 20002
  Number of variables: 80000
  Number of nonzeros: 160000
  Sense: maximize
Solver:
- Status: ok
  Termination condition: optimal
  Statistics:
    Branch and bound:
      Number of bounded subproblems: 1
      Number of created subproblems: 1
  Error rc: 0
  Time: 44.488093852996826
Solution:
- number of solutions: 0
  number of solutions displayed: 0

37071954.90391662

                     client_cnt
channel product
call    credit             1743
        credit_card        2257
sms     credit             3571
        credit_card        3429

In [10]:
df.head(10)

,client_id,product,channel,score,optimal_decision_1,optimal_decision_2
0,1,credit,call,0.999383,1.0,1.0
1,1,credit,sms,0.000081,0.0,0.0
2,1,credit_card,call,0.000171,0.0,0.0
3,1,credit_card,sms,0.000011,0.0,0.0
4,2,credit,call,0.000756,0.0,0.0
5,2,credit,sms,0.015672,1.0,1.0
6,2,credit_card,call,0.000797,0.0,0.0
7,2,credit_card,sms,0.004783,0.0,0.0
8,3,credit,call,0.000035,0.0,0.0
9,3,credit,sms,0.000164,0.0,0.0

In [20]:
#количество общих предложений двух решений
print(sum(np.array(optimal_decisions_1) * np.array(optimal_decisions_2)))

10002.0